// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourCarSlot.Infrastructure.EF.DatabaseContext;

#nullable disable

namespace YourCarSlot.Infrastructure.Migrations
{
    [DbContext(typeof(YCSDatabaseContext))]
    partial class YCSDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YourCarSlot.Domain.Entities.ParkingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c750373-6309-40c8-af68-973aaf8da562")
                        });
                });

            modelBuilder.Entity("YourCarSlot.Domain.Entities.ReservationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSlotRequesting")
                        .HasColumnType("int");

                    b.Property<int>("PartOfTheDayReservation")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserRequestingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ReservationRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81a130d2-502f-4cf1-a376-63edeb000e9f"),
                            BookingRequestTime = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Utc).AddTicks(7310),
                            CreatedAt = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7314),
                            DateModified = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7324),
                            ParkingSlotRequesting = 4,
                            PartOfTheDayReservation = 0,
                            PlateNumber = "4324-1345-53",
                            Reserved = true,
                            UserRequestingId = new Guid("25a130d2-502f-4cf1-a376-63edeb027212")
                        },
                        new
                        {
                            Id = new Guid("34a130d2-502f-4cf1-a376-63edeb092137"),
                            BookingRequestTime = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Utc).AddTicks(7328),
                            CreatedAt = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7330),
                            DateModified = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7331),
                            ParkingSlotRequesting = 1,
                            PartOfTheDayReservation = 0,
                            PlateNumber = "3123-466-221",
                            Reserved = true,
                            UserRequestingId = new Guid("25a130d2-502f-4cf1-a376-63edeb027212")
                        });
                });

            modelBuilder.Entity("YourCarSlot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36b99c90-b13d-11ed-afa1-0242ac120002"),
                            CreatedAt = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7581),
                            Email = "Wojciech@polo.pl",
                            FullName = "",
                            Password = "1234567",
                            Salt = "1",
                            Username = "DriftWojciech"
                        },
                        new
                        {
                            Id = new Guid("4428bf00-b13d-11ed-afa1-0242ac120002"),
                            CreatedAt = new DateTime(2023, 2, 21, 14, 29, 45, 88, DateTimeKind.Local).AddTicks(7587),
                            Email = "Kubus@polo.pl",
                            FullName = "",
                            Password = "1234567",
                            Salt = "4",
                            Username = "pogczamp"
                        });
                });

            modelBuilder.Entity("YourCarSlot.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MakeOfCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a417db6-b1f3-11ed-afa1-0242ac120002"),
                            MakeOfCar = "bmw",
                            PlateNumber = "23233-33"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
